=== 86lixuefeng/PN7462AU-FW_WriteCARD/PN7462AU/phHal/phCfg/xml/user_ee.dtd
<!--


                     Copyright (c), NXP Semiconductors

                        (C) NXP Semiconductors 2014,2015

          All rights are reserved. Reproduction in whole or in part is
         prohibited without the written consent of the copyright owner.
     NXP reserves the right to make changes without notice at any time.
    NXP makes no warranty, expressed, implied or statutory, including but
    not limited to any implied warranty of merchantability or fitness for any
   particular purpose, or that the use will not infringe any third party patent,
    copyright or trademark. NXP must not be liable for any loss or damage
                             arising from its use.

-->

<!-- Top element is UserEE : User EEPROM -->
<!ELEMENT UserEE (pages*) > <!-- USER EE has multiple pages -->
<!ATTLIST UserEE
   startAddress 	CDATA #REQUIRED
   endAddress 		CDATA #REQUIRED 
   product_name 	CDATA #REQUIRED 
   product_version 	CDATA #IMPLIED > 
		<!-- Starting address of EEPROM -->
		<!-- END Address of EEPROM -->
		<!-- Name of the product -->
		<!-- Version of the product -->

<!ELEMENT pages       (page*)>
<!ELEMENT page        (description,structure*)>
<!ELEMENT structure   (description?,(field*|array*)*)>
<!ELEMENT field       (description?,option*)>
<!ELEMENT array       (description?,option*)>
<!ATTLIST page
    name  CDATA #REQUIRED
>
<!ATTLIST structure
          name  CDATA #REQUIRED
          >

<!-- Single filed elements with 8/16/32 bits -->
<!ATTLIST field
          valuetype (int|hex) #REQUIRED
          value CDATA #REQUIRED
          type  (u8|u16|u32) #REQUIRED
          name  CDATA #REQUIRED
          >

<!-- Array of elements -->
<!ATTLIST array
          size  CDATA #REQUIRED
          type  (u8|u16|u32) #REQUIRED
          name  CDATA #REQUIRED
          value CDATA #REQUIRED
          valuetype (int|hex|cstring) #IMPLIED
          >

<!-- Describe what an values a particual filed would take -->
<!ELEMENT option   EMPTY>
<!ATTLIST option
          value       CDATA  #REQUIRED
          description CDATA  #IMPLIED
          >
<!ELEMENT name        (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== 86lixuefeng/PN7462AU-FW_WriteCARD/PN7462AU/phHal/phCfg/xml/user_ee.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--


                     Copyright (c), NXP Semiconductors

                        (C) NXP Semiconductors 2014,2015

          All rights are reserved. Reproduction in whole or in part is
         prohibited without the written consent of the copyright owner.
     NXP reserves the right to make changes without notice at any time.
    NXP makes no warranty, expressed, implied or statutory, including but
    not limited to any implied warranty of merchantability or fitness for any
   particular purpose, or that the use will not infringe any third party patent,
    copyright or trademark. NXP must not be liable for any loss or damage
                             arising from its use.

-->
<?xml-stylesheet type="text/xsl" href="user_ee.xslt" ?>
<!DOCTYPE page SYSTEM "user_ee.dtd"    [
        <!ENTITY ClifEE       SYSTEM "_ClifEE.xml" >

        <!-- Enter user_ee_RfAntennae_PLM.xml or user_ee_RfAntennae_ALM.xml -->
        <!ENTITY RfAntennae   SYSTEM "user_ee_RfAntennae.xml" >

        <!-- Enter user_ee_RfPcdShaping_65x65.xml or user_ee_RfPcdShaping_30x50.xml -->
        <!ENTITY RfPcdShaping SYSTEM "user_ee_RfPcdShaping.xml" >

        <!-- Enter user_ee_RfAPC_65x65.xml or user_ee_RfAPC_30x50.xml -->
        <!ENTITY RfAPC        SYSTEM "user_ee_RfAPC.xml" >

        <!-- Enter user_ee_RfDPC_/Antennae/_/TVDDVoltage/.xml -->
        <!ENTITY RfDPC      SYSTEM "user_ee_RfDPC.xml" >
    ]
>

<UserEE
  startAddress="0x201200"
  endAddress="0x201FFF"
  product_name="PN7462AU"
  product_version="MRA3"
  >

    <pages>
        <page name="ErrorMem" >
            <description>Error Memory written by ROM in case of error</description>
            <structure name="Err" >
                <description>Error information during ROM APIs</description>
                <array name="str_name" type="u8" size="36" value="IntentionallyEmpty" valuetype="cstring" >
                    <description>Reserved for MRA2 and MRA3</description>
                </array>
                <field name="dwCauseCode" type="u32" value="0x00" valuetype="hex" >
                    <description>Error information from ROM Boot</description>
                </field>
            </structure>
        </page>
        <page name="Ctrl" >
            <description>Master Control Block for EEPROM</description>
            <structure name="VerInfo" >
                <!-- Reviewed 2015.03.03 -->
                <description>
&lt;pre&gt;
    Version Information of the Layout
	Version 28.0.0: artf178091: [CR][FW][TXOCP] Load dependent RX gain control
	Version 27.0.0: artf203315 : The Default TVDD source config to be External. DPC 5V by default.
	Version 27.0.0: Clif EEPROM 1.9.2v Settings.
	Version 26.0.0: artf157683 : Changing the wWaitTime of Tx Ldo Params. [15:14] : Lfo Clock Value and [13:0] : Waiting Time after TxLdo is started.
	Version 25.5.0: artf156243 : Update according to the Analysis Information.
	Version 25.4.0: wWaitTime value for Tx Ldo start ir changed from 250us to 1100us.
    Version 25.3.0: dwTidtTimeAdjust field added.
    Version 25.2.0: RRDD value changed from 28us to 50us and dwExtRfOnTime values to 302us.
    Version 25.1.0: Adding the RRDD and Fdt values for Jewel.
    Version 25.0.0: Clif EEPROM 1.9v settings
    &lt;hr /&gt;
    Version 24.0.2: [RC4] CLIF_ANA_NFCLD_REG.CM_RFL_NFC set to 7.  [MRA3] v1.8.3 of EEPROM
    Version 24.0.1: Refactored dwFelicaRxRMSigproTime
    Version 24.0.0: Removed the Rf On and Off De-bouncing structure. 
                  : Added Rf Inter-Op timings structure and Rf hal timings 
                  : for different algos.
    Version 23.9.0: CLIF_ANA_NFCLD_REG.CM_RFL_NFC value changed from 7 to 3
    Version 23.8.0: [MRA2] v1.8   of EEPROM
    Version 23.7.0: [MRA2] v1.7.4 of EEPROM
    Version 23.6.0: [MRA2] ClkGenClifClockStart->ClkModeAlmCm set to 0x50
&lt;/pre&gt;
                </description>
                <field  name="major" type="u16" value="28" valuetype="int" >
                    <!-- Change in major version means total in-compatibility -->
                    <description>Major Version</description>
                </field>
                <field  name="minor" type="u8" value="0" valuetype="int" >
                    <!-- Change in minor version means new fields have been added -->
                    <description>Minor Version</description>
                </field>
                <field  name="development" type="u8" value="0" valuetype="int" >
                    <!-- Change in minor version means values have changed -->
                    <description>Development Version</description>
                </field>
                <array name="str_name" type="u8" size="32" value="Rf#v1.9" valuetype="cstring" >
                    <description>Canonical name to identify the EE Layout</description>
                </array>
            </structure>
        </page>
        <page name="Boot" >
            <description>These values are used during during Boot up and applied to HW IPs</description>
            <structure name="RNG" >
                <description>Random Number Generator. \see phhalRng_Init</description>
                <field name="bTrngFeedTimeout" type="u8" value="0x26" valuetype="hex" >
                    <description>Programmable wait time to release gated clocks feeding the TRNG</description>
                </field>
            </structure>
            <structure name="ClkGen" >
                <description>Clock Generator.  \ref phhalClkGen_Init</description>
                <field name="wXtalActivationTimeOut" type="u16" value="2000" valuetype="int" >
                    <description>dwXtalActivationTimeOut Activation time out value</description>
                </field>
                <field name="eSource" type="u8" value="0x00" valuetype="hex" >
                    <description>eSource Clock source selection, \see phhalClkGen_Source_t</description>
                </field>
                <field name="bKickOnError" type="u8" value="0x00" valuetype="hex" >
                    <description>bKickOnError Kick on error.</description>
                </field>
            </structure>
            <structure name="PcrPwrTempConfig" >
                <!--  Reviewed structure contents PGh: 2015.03.09 -->
                <description>Power Clock Reset Temperature Configuration related to \see phhalPcr_PwrTempConfig_t

                \warning This structure is tightly linked to \ref phhalPcr_PwrTempConfig_t
                </description>
                <field name="bUseTempSensor0" type="u8" value="0" valuetype="int" >
                    <description>Flag to indicate to use temperature sensor 0 or not</description>
                    <option value="0" description="Disabled" />
                    <option value="1" description="Enabled" />
                </field>
                <field name="bUseTempSensor1" type="u8" value="0" valuetype="int" >
                    <description>Flag to indicate to use temperature sensor 1 or not</description>
                    <option value="0" description="Disabled" />
                    <option value="1" description="Enabled" />
                </field>
                <field name="bLowTempTarget0" type="u8" value="3" valuetype="int" >
                    <option value="0" description="135" />
                    <option value="1" description="130" />
                    <option value="2" description="125" />
                    <option value="3" description="120" />
                </field>
                <field name="bLowTempTarget1" type="u8" value="3" valuetype="int" >
                    <option value="0" description="135" />
                    <option value="1" description="130" />
                    <option value="2" description="125" />
                    <option value="3" description="120" />
                </field>
                <field name="bHighTempTarget0" type="u8" value="0" valuetype="int" >
                    <option value="0" description="135" />
                    <option value="1" description="130" />
                    <option value="2" description="125" />
                    <option value="3" description="120" />
                </field>
                <field name="bHighTempTarget1" type="u8" value="0" valuetype="int" >
                    <option value="0" description="135" />
                    <option value="1" description="130" />
                    <option value="2" description="125" />
                    <option value="3" description="120" />
                </field>
            </structure>
            <structure name="PcrPwrDown">
                <!-- Added on 2015.08.10:  See SC3476: [PCR HAL API Change] Power Down Setting during USB should be provided as input parameter -->
                <description>See \ref phhalPcr_PwrDown_Setting_t

It is a 32 bit value bit-file created by ORing enums of type \ref phhalPcr_PwrDown_Setting_t used to select which settings must be applied to reduce power consumption during Suspend</description>
                <field valuetype="hex" name="dwPwrDownSettings" type="u32" value="0x7FFFFFFF">
                    <description>
                        0x7FFFFFFF : E_APPLY_ALL_SETTNGS. i.e.  all power reduction settings will be applied during Suspend
                    </description>
                </field>
            </structure>
            <structure name="TxAnaStandByConfig">
                <!-- Reviewed structure contents PGh: 2015.03.09 -->
                <description> TxAna register settings for standby  \see phhalPcr_TxAnaStandByConfig_t</description>
                <field name="dwAnaTxStandByValue" type="u32" value="0F" valuetype="hex" >
                    <description>
                        To hold CLIF standby GSN value selection
                    </description>
                </field>
                <field name="dwAnaTxProtStandByValue" type="u32" value="03" valuetype="hex" >
